services:
  postgres:
    image: bitnami/postgresql:17.2.0
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    environment:
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/bitnami/postgresql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 8090:8090
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./backend:/app
